Failure # 1 (occurred at 2025-10-27_11-31-47)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=31657, ip=127.0.0.1, actor_id=4ddf763227c37bf743434ad501000000, repr=PPO(env=<class 'rllib_env.berth_allocation_env.BerthAllocationMultiAgentEnv'>; env-runners=0; learners=0; multi-agent=True))
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 536, in __init__
    super().__init__(
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 158, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 644, in setup
    self.env_runner_group = EnvRunnerGroup(
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/env/env_runner_group.py", line 196, in __init__
    self._setup(
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/env/env_runner_group.py", line 290, in _setup
    self._local_env_runner = self._make_worker(
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/env/env_runner_group.py", line 1267, in _make_worker
    return self.env_runner_cls(**kwargs)
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env_runner.py", line 112, in __init__
    self.make_env()
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env_runner.py", line 830, in make_env
    self.env = make_vec(
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/env/vector/registration.py", line 69, in make_vec
    env = SyncVectorMultiAgentEnv(
  File "/Users/duan/miniforge3/envs/marl-task/lib/python3.9/site-packages/ray/rllib/env/vector/sync_vector_multi_agent_env.py", line 39, in __init__
    self.single_observation_spaces = dict(
TypeError: 'Box' object is not iterable
